name: Web Site Publication

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Build Site
        uses: DivLoic/hugo-actions@0.0.1
        with:
          args: -e PROD
          hugoVersion: 'extended_0.125.7'

      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.LMD_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
