name: Web Site Publication

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Build Site
        uses: chabad360/hugo-actions@master
        with:
          args: -e PROD

      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.LMD_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public