name: Web Site Publication

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Hugo Setup
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.125.7'
          extended: true

      - name: Hugo Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3.0.0
        if: github.ref == 'refs/heads/main'
        env:
          PERSONAL_TOKEN: ${{ secrets.LMD_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
