name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Checkout Submodules
        uses: textbook/git-checkout-submodule-action@2.1.1

      - name: Build Site
        uses: chabad360/hugo-actions@master