name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Hugo Setup
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.125.7'
          extended: true

      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Asciidoctor Setup
        run: gem install asciidoctor

      - name: Build Hugo
        run: |
          alias asciidoctor="asciidoctor --attribute=experimental=true --attribute=icons=font"
          hugo --gc --minify --cleanDestinationDir
