name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Build Site
        uses: chabad360/hugo-actions@master